/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyCard: typeof import('./components/ApiKeyCard.vue')['default']
    AppStatisticsCard: typeof import('./components/AppStatisticsCard.vue')['default']
    ModelUsage: typeof import('./components/ModelUsage.vue')['default']
    ReacentActivity: typeof import('./components/ReacentActivity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
