version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: llmbridge
      MYSQL_USER: blaz
      MYSQL_PASSWORD: blaz
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "80"
    environment:
      PMA_HOST: db
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
